apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  DATABASE_HOST: {{ .Release.Name }}-appointment-db
  DATABASE_PORT: "5432"
  FRONTEND_URL: "http://appointment.local"
