apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.credentials.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.credentials.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.database.credentials.dbName | b64enc | quote }}
